### ISSUE TITLE
glitches on Apple II

### ISSUE THREAD

**Issue by lazy-schemer** [StewBC/cc65-Chess#10] opened 2024-01-05 14:08 UTC
![broken_pieces](https://github.com/StewBC/cc65-Chess/assets/37852556/94f6b704-58f6-4d77-90b4-1ba132b85149)

I built it like this: 
```
make OPTIONS=optsize TARGETS=apple2 dsk
```

**Comment by lazy-schemer** [comment] 2024-01-05 14:10
@oliverschmidt   could you give me some advices?

**Comment by oliverschmidt** [comment] 2024-01-05 15:40
No good idea :-(

Just some random ideas:
* Maybe the code makes assumptions which aren't met on the emulator used. I'd try the same binary with i.e. AppleWin.
* Maybe cc65 has changed something over time. I'd try to build with a cc65 HEAD around the time the Apple II port was done.

**Comment by StewBC** [comment] 2024-01-05 18:09
I can confirm that the issue does indeed now happen.  With optsize as decsribed and with optspeed, when drawing the board and it gets to the garbled pieces, the game will crash.  I can't look into it right now to make sure this is the issue but I when I look at a version that I previously built, and that does work, it is 24976 bytes.  The version I built with a newer compiler (cl65 V2.19 - Git 1093d16 - mabe a month or two ago?) generated an executable of 25961 bytes. I thus suspect a compiler change.

When I have time, I will investigate further (I always kept the previous compiler and just with the last time I updated I didn't - now I sure wish I had ;)

**Comment by lazy-schemer** [comment] 2024-01-09 04:58
Hello
I was able to build it with a previous commit of cc65 ( 2a421396, 2019/11/29 ) 
![cc65_2a421396](https://github.com/StewBC/cc65-Chess/assets/37852556/573d9203-ded3-4404-a38c-8106192ceb4e)
the reason is still unclear, but it would be ok with me 😀

**Comment by oliverschmidt** [comment] 2024-01-09 07:43
* The change in the binary file size is no surprise. If you take a look at the cc65 change log, you'll notice that the compiler basically changes all the time.
* Needless to say that it would be great to bisect this regression. If it is a cc65 problem it would of course be desirable to have a cc65 issue opened. When being able to pinpoint the cc65 change that introduced it, I guess it wouldn't be necessary to additionally create a minimal reproduction program.
* I think for everybody reading this it would be great if a small set of moves were given that trigger the issue.

**Comment by StewBC** [comment] 2024-01-09 09:42
From Oliver's list:

1) ACK

2) I did this bisect now - here is the result - The first bad commit:
commit 8b6d78a075dafde8583c4992d37995d9b4c9db97
Author: acqn <acqn163@outlook.com>
Date:   Mon Mar 1 22:11:22 2021 +0800

    Added Opt_a_tosbitwise for 8-bit bitwise operations.

 src/cc65/coptstop.c | 83 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 83 insertions(+)
 
**But this doesn't make sense to me** because I started with _head_ today as bad and as good I used:
commit e5f4ca6b898bf581751901fd5792764adfb7730a
Merge: 128b15a71 1f9594560
Author: Bob Andrews <mrdudz@users.noreply.github.com>
Date:   Wed Apr 19 15:07:16 2023 +0200

    Merge pull request #2058 from icepic/patch-1

    Update lynxsprite.c

So bad is today and good was Apr 19, 2023 but bisect says first bad commit was 2021?  This was my first time using bisect.  I suppose that the 2021 commits didn't get merged till after Apr 2023?  I don't know how to look to see and my first attempts at finding the asnwers in Google didn't work out - and now I am out of time.

 
 3) Simply running the game and pressing a key on the title screen advances to the board.  The bottom (white) pieces stick out above the menu.  These pieces can be seen to be corrupt.

**Comment by lazy-schemer** [comment] 2024-01-09 10:16
Pieces are broken since PR 2240 

OK
bb1b5c36 Bob Andrews <mrdudz@users.noreply.github.com> on 2023/10/18 at 19:51
OK 
Merge pull request #2238 from acqn/BoolOptFix
8e6c0c14 Bob Andrews <mrdudz@users.noreply.github.com> on 2023/10/26 at 20:06
ERROR
Merge pull request #2240 from acqn/BitwiseOpt
a8d00bfa Bob Andrews <mrdudz@users.noreply.github.com> on 2023/10/26 at 23:53
ERROR
316ae886 Bob Andrews <mrdudz@users.noreply.github.com> on 2023/10/26 at 23:56

disks I tested are here.
[disk2.zip](https://github.com/StewBC/cc65-Chess/files/13872270/disk2.zip)

**Comment by lazy-schemer** [comment] 2024-01-09 10:19
I built them on Intel Mac.
```
> gcc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by oliverschmidt** [comment] 2024-01-10 00:53
Can you please check if https://github.com/StewBC/cc65-Chess/pull/12 makes a difference?

**Comment by lazy-schemer** [comment] 2024-01-10 06:07
still problem 

build with cc65 HEAD 2024/01/09 at 7:02 
* cc65-Chess_patch-1_cc65_HEAD_ERR.dsk - broken

build with cc65 8e6c0c14 2023/10/26 at 20:06
* cc65-Chess_patch-1_cc65_8e6c0c14_OK.dsk - OK

cc65's differences between  8e6c0c14 (makes OK build) and a8d00bfa (makes error build)
I hope this can be a hint.

![cc65_differences](https://github.com/StewBC/cc65-Chess/assets/37852556/11a9c6d2-8e15-40b3-a053-2158b12bac1a)


[patch-1_builds.zip](https://github.com/StewBC/cc65-Chess/files/13883531/patch-1_builds.zip)

**Comment by iss000** [comment] 2024-01-11 14:46
The issue appears when mixing XOR and the result from logical operation.
The fix changes from:
inv = blackWhite ^ (piece & PIECE_WHITE) != 0;
to
inv = blackWhite ^ (!!(piece & PIECE_WHITE) != 0);
in src/apple2/platA2.c (line 218)
![Screenshot_20240111_163213](https://github.com/StewBC/cc65-Chess/assets/1128663/6331413d-7187-4253-9563-adb56379e8ad)
I'm using latest cc65 build from sources.

EDIT: I didn't checked if other platforms are affected.

**Comment by lazy-schemer** [comment] 2024-01-11 15:15
my build also works fine! 😄  thank you !!

**Comment by StewBC** [comment] 2024-01-11 19:56
Thank you @iss000 - that does indeed fex the problem.  I opted for the line: inv = blackWhite ^ !((piece & PIECE_WHITE) != 0); simply because I would never think to use !!

**Closed as completed** 2024-01-11 19:56 UTC

**Comment by oliverschmidt** [comment] 2024-01-11 20:18
Sorry for being slow on the take-up, but isn't `(piece & PIECE_WHITE) != 0` already a boolean expression? Can someone please explain what the two changes (the one proposed by @iss000 and the one @StewBC opted for) are doing?

**Comment by StewBC** [comment] 2024-01-11 21:13
It's an order of precedence issue.  The orifinal code makes inv == 128 and the new code makes it == 1 if piece = 0 and PIECE_WHITE == 128.  AT least, I think that's what's going on.  Empirically tested I can say that inv == 128 and not 1 in the old vs new code.

**Comment by oliverschmidt** [comment] 2024-01-11 22:36
Thanks for the feedback. Sorry for not being precise enough: I'm wondering __why__ it is that way.

**Comment by iss000** [comment] 2024-01-11 23:05
Just for the record: my favorites actually are:
`inv = blackWhite ^ (piece & PIECE_WHITE ? 1:0);`
or
`inv = blackWhite ^ ((piece>>7)&1);`
Assuming that '!' returns always '0' or '1' isn't always portable.
There are compilers which return '0' or '-1' ... 😄

**Comment by oliverschmidt** [comment] 2024-01-11 23:15
@iss000: Am I right to presume that your recent comment is no answer to my question but rather refers to @StewBC's code?

**Comment by StewBC** [comment] 2024-01-12 02:59
This code below produces, on MSVC and gcc, the output:
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
but on the Apple II it produces:
![image](https://github.com/StewBC/cc65-Chess/assets/869735/747783ae-b60f-4871-a2ba-f89890a25f37)

If I go to an "old working" version of cc65, I get the same output as in MSVC and gcc from cc65.  I don't know what the standards say about any of this, but cc65 has changed its behaviour.

This code was used on the Apple II but with cstdio and cprintf, and with a while(!cgetc()){;} at the end of main so I could see the output.

```
#include <stdio.h>

#define PIECE_WHITE 128
unsigned char gChessBoard[8][8];

void plat_DrawSquare(char position)
{
    char inv;
    char y = position / 8, x = position & 7;
    char piece = gChessBoard[y][x];
    char blackWhite = !((x & 1) ^ (y & 1));

    if(piece) {
        inv = blackWhite ^ (piece & PIECE_WHITE) != 0;
    } else {
        inv = 0;
    }
    if(!(x%8)) {
        printf("\n\r");
    }
    printf("%0d ", inv);
}

void main() {
    int i;
    for(i = 0; i < 16; i++) {
        gChessBoard[i/8][i%8] = 0;
        gChessBoard[6+i/8][i%8] = PIECE_WHITE;
    }
    for(i = 0; i < 16; i++) {
        plat_DrawSquare(i);
    }
    for(i = 0; i < 16; i++) {
        plat_DrawSquare(6*8+i);
    }
}
```

**Comment by oliverschmidt** [comment] 2024-01-12 18:51
Just for the record:
* cgetc() waits for a keyypress so there's no need for a while() loop.
* Building with the default options and starting the resulting program from BASIC makes it return to BASIC so any output stays visible.

The latter implies that there's no need to change the source code of the program above in any way for the Apple II.

**Comment by oliverschmidt** [comment] 2024-01-12 19:10
> If I go to an "old working" version of cc65, I get the same output as in MSVC and gcc from cc65.

That's the reason why it worked before.

> I don't know what the standards say about any of this, but cc65 has changed its behaviour.

Even if the current cc65 behavior is covered by the standard it might still be that the cc65 team isn't aware of the change in behavior and considers it desirable to revert to the former behavior. I personally even assume that they see it this way.

My suggestion would be therefore to further reduce your program to the bare minimum showing the difference to GCC and open a cc65 issue (incl. the info which commit changed the behavior).

**Comment by colinleroy** [comment] 2024-02-02 16:44
Hi,
FYI, the regression has been fixed upstream in https://github.com/cc65/cc65/pull/2398, in case you want to remove the workaround commit.

**Comment by oliverschmidt** [comment] 2024-02-02 17:05
@colinleroy Thanks for taking care of that! It's actually a nice show case for the usefulness of actually communicating with the cc65 team 😃

**Comment by colinleroy** [comment] 2024-02-02 18:15
> @colinleroy Thanks for taking care of that! It's actually a nice show case for the usefulness of actually communicating with the cc65 team 😃

And that `git bisect` is a godsend :smile:

**Comment by colinleroy** [comment] 2024-02-02 18:42
> So bad is today and good was Apr 19, 2023 but bisect says first bad commit was 2021? This was my first time using bisect. I suppose that the 2021 commits didn't get merged till after Apr 2023? I don't know how to look to see and my first attempts at finding the asnwers in Google didn't work out - and now I am out of time.

You suppose correctly, the PR was opened in October 2023 with commits two years old :) 

For what it's worth, you can find the history with `gitk`, searching for the commit hash, it'll mention when it got merged:
![image](https://github.com/StewBC/cc65-Chess/assets/1016317/6d32eb3f-1b07-473d-b3a1-3ec00c18f6cf)

**Comment by StewBC** [comment] 2024-02-03 01:47
@colinleroy Thank you!  I appreciate you sorting this.  It still sat in my inbox as something I needed to do when I finished what I am busy doing :)
Now I'll fix the chess commit when I am finished doing what I am busy doing ;)
Anyway, much appreciated!
